repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
      -   id: check-yaml
      -   id: end-of-file-fixer
      -   id: trailing-whitespace
      -   id: check-merge-conflict
      -   id: detect-private-key
      -   id: name-tests-test
  # -   repo: https://github.com/psf/black
  #     rev: 23.3.0
  #     hooks:
  #       - id: black
  #         language_version: python3.10
  -   repo: https://github.com/pre-commit/mirrors-autopep8
      rev: 'v2.0.2'  # Use the sha / tag you want to point at
      hooks:
      -   id: autopep8
  -   repo: local
      hooks:
        - id: pylint
          name: pylint
          entry: pylint --exit-zero --fail-on=F,E src/
          language: system
          always_run: true
          pass_filenames: false
        -   id: conda-export
            name: conda-export
            entry: python -m environment
            language: python
            additional_dependencies: [toml, pyyaml]
            pass_filenames: false
            always_run: true
